import Head from 'next/head';
import { useContext, useEffect } from 'react';
import Header from '../components/Header';
import { CART_RESET } from '../utils/redux/constants/cartConstants';
import { KEY_CART_LOCALSTORAGE } from '../utils/redux/constants/globalConstants';
import { Store } from '../utils/redux/Store';

function Layout({ title, children }) {
  const { state, dispatch } = useContext(Store);
  const baseTitle = 'Next.JS E-commerce';

  useEffect(() => {
    // To make cart items stay when refresh page
    const cartLocalStorage = localStorage.getItem(KEY_CART_LOCALSTORAGE);
    if (cartLocalStorage) {
      dispatch({ type: CART_RESET, payload: JSON.parse(cartLocalStorage) });
    }
  }, []);

  return (
    <>
      <div>
        <Head>
          <title>
            {title ? `${title} - ${baseTitle}` : 'Next.JS E-commerce'}
          </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="mx-auto my-0 flex flex-col items-start justify-start min-h-screen">
          <header>
            <Header />
          </header>
          <main className="container mt-20 md:mt-20 flex justify-center mx-auto px-4">
            {children}
          </main>
          <footer className="flex w-full mt-20 justify-center items-center ">
            <div className="fixed bottom-0 w-full h-14 pt-5 text-center align-text-middle bg-white/95 shadow-2xl shadow-gray-800 w-full align-middle ">
              Copyright ©2022 Sunyrora
            </div>
          </footer>
        </div>
      </div>
    </>
  );
}

export default Layout;
