import Head from 'next/head';
import Header from '../components/Header';

function Layout({ title, children }) {
  const baseTitle = 'Next.JS E-commerce';
  return (
    <>
      <div>
        <Head>
          <title>
            {title ? `${title} - ${baseTitle}` : 'Next.JS E-commerce'}
          </title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="mx-auto my-1 flex flex-col justify-between min-h-screen">
          <header>
            <Header />
          </header>
          <main className="container m-auto mt-4 px-4">{children}</main>
          <footer className="flex h-10 justify-center items-center shadow-inner">
            <p>Copyright ©2022 Sunyrora </p>
          </footer>
        </div>
      </div>
    </>
  );
}

export default Layout;
